name: story_view
description: "A Flutter package that lets you easily create beautiful, interactive story views similar to social media apps."
version: 1.0.0
homepage: https://github.com/MohammadAssaf10/story_view
repository: https://github.com/MohammadAssaf10/story_view

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  better_player_plus: ^1.1.5
  wakelock_plus: ^1.4.0
  flutter_cache_manager: ^3.4.1
  percent_indicator: ^4.2.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
